[package]
name = "sjt"
human_name = "Ter Sami"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sjt]
filename = "sjt-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sjt"
platform = "windows"
uuid = "319902AA-912C-43A9-AB0D-F0D945858FD7"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sjt"
package = "speller-sjt"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sjt-mso"
platform = "windows"
uuid = "2A3ABFED-468B-4F90-8903-0B1416904375"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sjt"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
